#!/usr/bin/env Rscript

################################################################################
# RNAi synthetic-lethality screening by microsatellite status
#
# Purpose
#   Identify and run GRETTA RNAi synthetic-lethality (SL) screens for
#   patient-aligned loss-of-function (LOF) contexts separately in
#   microsatellite-stable (MSS) and microsatellite-instability (MSI)
#   DepMap cell lines.
#
# This script uses the screenable contexts identified in Script 01 and runs
# the same RNAi analysis for each microsatellite group by changing only the
# cell-line subset.
#
# Starting point
#   Supplemental Table S1B: all biallelic loss-of-function (BLOF) alterations
#   identified in the POG cohort.
#
# Prerequisites
#   1. Supplemental Table S1B with columns:
#        POG_patient_id, POG_sample_id, POG_sample_disease, BLOF_gene,
#        amino_acid_p, mut_data
#   2. The table of screenable RNAi contexts generated by Script 01.
#   3. GRETTA-formatted DepMap 23Q4 RNAi dependency data.
#   4. A CSV assigning each DepMap model to inferred MSS/MSI status.
#   5. Per-gene `cell_line_groups.csv` files generated during DepMap
#      LOF-context definition. Each file must contain:
#        DepMap_ID, disease, Group
#      where "Control" denotes the comparison group and non-control groups
#      denote LOF contexts.
#   6. Open Targets tractability annotations (v23.02 used in the study).
#
# Outputs
#   - individual GRETTA RNAi screen results
#   - Tier 1/2/3 annotated results for each screen
#   - combined Tier 1/2/3 results across POG-aligned contexts
#   - optional screen plots
#
# Notes
#   - A screen requires >= 3 mutant and >= 3 control cell lines.
#   - "pancan" includes all eligible cancer cell lines in the relevant
#     microsatellite-status subset.
#   - MSS/MSI status is used to stratify the DepMap models; the SL comparison
#     remains LOF versus control within each context.
#   - HomDel is preferred as the BLOF mutant group; T-HetDel is used only when
#     HomDel is insufficient. HetDel is never used.
#   - The tier definitions below reproduce the RNAi criteria used in the
#     study.
################################################################################

suppressPackageStartupMessages({
  library(tidyverse)
  library(GRETTA)
  library(janitor)
})

# ------------------------------------------------------------------------------
# User-defined paths and analysis parameters
# ------------------------------------------------------------------------------

supp_table_s1b_file <- "path/to/Supplemental_Table_S1B.csv"
gretta_data_dir <- "path/to/GRETTA_data/23Q4/data"
lof_context_dir <- "path/to/individual_genes"
tractability_file <- "path/to/tractability_v23-02.tsv"
output_dir <- "results/rnai"

screenable_file <- file.path(
  output_dir,
  "RNAi_screenable_POG_BLOF_contexts.csv"
)

min_group_size <- 3L
n_perm <- 10000L
core_num <- 8L
make_plots <- TRUE

# ------------------------------------------------------------------------------
# Load and validate inputs
# ------------------------------------------------------------------------------

supp_table_s1b <- read_csv(supp_table_s1b_file, show_col_types = FALSE)

required_s1b_columns <- c(
  "POG_patient_id",
  "POG_sample_id",
  "POG_sample_disease",
  "BLOF_gene",
  "amino_acid_p",
  "mut_data"
)

missing_s1b_columns <- setdiff(required_s1b_columns, colnames(supp_table_s1b))
if (length(missing_s1b_columns) > 0) {
  stop(
    "Supplemental Table S1B is missing required columns: ",
    paste(missing_s1b_columns, collapse = ", ")
  )
}

pog_blof_genes <- supp_table_s1b %>%
  filter(!is.na(BLOF_gene), BLOF_gene != "") %>%
  pull(BLOF_gene) %>%
  unique()

load(file.path(gretta_data_dir, "rnai_long.rda"))

ms_status_df <- read_csv(
  file.path(gretta_data_dir, "inferred_MS_status.csv"),
  show_col_types = FALSE
) %>%
  filter(Inferred_MS_status %in% c("inferred_MSS", "inferred_MSI")) %>%
  distinct(DepMap_ID, Inferred_MS_status)

screenable_contexts <- read_csv(
  screenable_file,
  show_col_types = FALSE
) %>%
  filter(
    is_screenable,
    GeneName %in% pog_blof_genes
  )

# Script 01 applies the study BLOF hierarchy: HomDel is preferred and
# T-HetDel is used only when HomDel is insufficient. HetDel is never screened.
invalid_blof_groups <- screenable_contexts %>%
  filter(!mut_group %in% c("HomDel", "T-HetDel"))

if (nrow(invalid_blof_groups) > 0) {
  stop(
    "`screenable_file` contains mutant groups outside the study BLOF definition. ",
    "Expected only HomDel or T-HetDel. Re-run Script 01."
  )
}

# ------------------------------------------------------------------------------
# Open Targets tractability annotation
# ------------------------------------------------------------------------------

opentarget_df <- read_tsv(
  tractability_file,
  show_col_types = FALSE
) %>%
  janitor::clean_names()

required_tractability_columns <- c(
  "symbol",
  "protein_names",
  "top_bucket_sm",
  "category_sm",
  "top_bucket_ab",
  "category_ab",
  "top_bucket_protac",
  "category_protac",
  "top_bucket_othercl",
  "category_othercl"
)

missing_tractability_columns <- setdiff(
  required_tractability_columns,
  colnames(opentarget_df)
)

if (length(missing_tractability_columns) > 0) {
  stop(
    "Open Targets input is missing required columns: ",
    paste(missing_tractability_columns, collapse = ", ")
  )
}

compound_tractability <- opentarget_df %>%
  select(all_of(required_tractability_columns)) %>%
  mutate(
    Drug_group = case_when(
      # WRN was manually assigned to Group 1 in the original analysis.
      symbol == "WRN" ~ "Group_1",

      category_sm == "Clinical_Precedence_sm" ~ "Group_1",
      category_ab == "Clinical_Precedence_ab" ~ "Group_1",
      category_protac == "Clinical_Precedence_protac" ~ "Group_1",
      category_othercl == "Clinical_Precedence_othercl" ~ "Group_1",

      category_sm == "Discovery_Precedence_sm" ~ "Group_2",
      category_ab == "Predicted_Tractable_ab_High_confidence_ab" ~ "Group_2",
      category_protac == "Literature_Precedence_protac" ~ "Group_2",

      category_sm == "Predicted_Tractable_sm" ~ "Group_3",
      category_ab == "Predicted_Tractable_ab_Medium_to_low_confidence_ab" ~ "Group_3",
      category_protac == "Discovery_Opportunity_protac" ~ "Group_3",

      TRUE ~ NA_character_
    )
  )

group_1_genes <- compound_tractability %>%
  filter(Drug_group == "Group_1") %>%
  pull(symbol)

group_2_genes <- compound_tractability %>%
  filter(Drug_group == "Group_2") %>%
  pull(symbol)

group_3_genes <- compound_tractability %>%
  filter(Drug_group == "Group_3") %>%
  pull(symbol)

# ------------------------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------------------------

safe_name <- function(x) {
  str_replace_all(x, "\\s|/", "_")
}

get_context_ids <- function(
    cell_lines,
    mutant_group,
    disease,
    ms_label,
    available_rnai_ids,
    ms_status_df) {

  inferred_status <- if_else(
    ms_label == "MSS",
    "inferred_MSS",
    "inferred_MSI"
  )

  ms_ids <- ms_status_df %>%
    filter(Inferred_MS_status == inferred_status) %>%
    pull(DepMap_ID)

  context_lines <- cell_lines %>%
    filter(
      Group %in% c("Control", mutant_group),
      DepMap_ID %in% available_rnai_ids,
      DepMap_ID %in% ms_ids
    )

  if (disease != "pancan") {
    context_lines <- context_lines %>%
      filter(.data$disease == disease)
  }

  list(
    mutant_id = context_lines %>%
      filter(Group == mutant_group) %>%
      pull(DepMap_ID) %>%
      unique(),

    control_id = context_lines %>%
      filter(Group == "Control") %>%
      pull(DepMap_ID) %>%
      unique()
  )
}

annotate_rnai_results <- function(screen_results_permed) {

  screen_results_permed %>%
    mutate(
      # RNAi dependency scores are oriented such that lower values indicate
      # greater dependency; therefore Mutant < Control is classified as SL.
      GI_type = if_else(
        Mutant_median < Control_median,
        "SL",
        "AL"
      ),

      # RNAi-specific tier thresholds used in the final analysis.
      GI_tier = case_when(
        Pval < 0.05 &
          Pval_perm_adj < 0.01 &
          abs(Median_diff) > 0.5 &
          (abs(Control_median) > 0.5 | abs(Mutant_median) > 0.5) ~ "Tier_1",

        Pval < 0.05 &
          Pval_perm_adj < 0.05 &
          abs(Median_diff) > 0.5 &
          (abs(Control_median) > 0.5 | abs(Mutant_median) > 0.5) ~ "Tier_2",

        Pval < 0.05 &
          Pval_perm_adj < 0.05 &
          abs(Median_diff) > 0.3 ~ "Tier_3",

        TRUE ~ NA_character_
      ),

      # Tier 1/2/3 synthetic-lethal candidates must also show sufficient
      # dependency in the mutant group.
      GI_tier = case_when(
        GI_type == "SL" &
          GI_tier == "Tier_1" &
          Mutant_median >= -0.5 ~ "Tier_3",

        GI_type == "SL" &
          GI_tier == "Tier_2" &
          Mutant_median >= -0.5 ~ "Tier_3",

        TRUE ~ GI_tier
      ),

      # Preserve the tractability grouping used in the original analysis.
      Drug_group = case_when(
        GeneNames %in% group_1_genes ~ "Group_1",
        GeneNames %in% group_2_genes ~ "Group_2",
        GeneNames %in% group_3_genes ~ "Group_3",
        TRUE ~ "Group_3"
      ),

      GI_tier = factor(
        GI_tier,
        levels = c("Tier_1", "Tier_2", "Tier_3")
      ),

      Drug_group = factor(
        Drug_group,
        levels = c("Group_1", "Group_2", "Group_3")
      ),

      Priority_class = case_when(
        GI_tier == "Tier_1" & Drug_group == "Group_1" ~ "Class_A",
        GI_tier == "Tier_2" & Drug_group == "Group_1" ~ "Class_B",
        GI_tier == "Tier_1" ~ "Class_C",
        GI_tier %in% c("Tier_1", "Tier_2") ~ "Class_D",
        TRUE ~ NA_character_
      ),

      Priority_class = factor(
        Priority_class,
        levels = c("Class_A", "Class_B", "Class_C", "Class_D")
      )
    )
}

# ------------------------------------------------------------------------------
# Output directories
# ------------------------------------------------------------------------------

intermediate_dir <- file.path(output_dir, "intermediate_files")
results_dir <- file.path(output_dir, "GI_results")
plots_dir <- file.path(output_dir, "GI_plots")

dir.create(intermediate_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(results_dir, recursive = TRUE, showWarnings = FALSE)

if (make_plots) {
  dir.create(plots_dir, recursive = TRUE, showWarnings = FALSE)
}

available_rnai_ids <- unique(rnai_long$DepMap_ID)

# ------------------------------------------------------------------------------
# Run POG-aligned RNAi screens
# ------------------------------------------------------------------------------

for (i in seq_len(nrow(screenable_contexts))) {

  context <- screenable_contexts[i, ]

  gene <- context$GeneName
  mutant_group <- context$mut_group
  disease <- context$disease
  ms_label <- context$MS_status

  group_file <- file.path(
    lof_context_dir,
    gene,
    "cell_line_groups.csv"
  )

  if (!file.exists(group_file)) {
    next
  }

  cell_lines <- read_csv(group_file, show_col_types = FALSE)

  ids <- get_context_ids(
    cell_lines = cell_lines,
    mutant_group = mutant_group,
    disease = disease,
    ms_label = ms_label,
    available_rnai_ids = available_rnai_ids,
    ms_status_df = ms_status_df
  )

  if (
    length(ids$mutant_id) < min_group_size ||
      length(ids$control_id) < min_group_size
  ) {
    next
  }

  context_label <- paste(
    gene,
    mutant_group,
    safe_name(disease),
    ms_label,
    sep = "_"
  )

  final_file <- file.path(
    results_dir,
    paste0(
      context_label,
      "_GI_perms_annotated_prioritised.csv"
    )
  )

  if (file.exists(final_file)) {
    message("Skipping existing result: ", basename(final_file))
    next
  }

  message(
    "Running RNAi screen ", i, "/", nrow(screenable_contexts), ": ",
    gene, " | ", mutant_group, " | ", disease, " | ", ms_label,
    " (", length(ids$mutant_id), " mutant; ",
    length(ids$control_id), " control)"
  )

  screen_results <- GRETTA::GI_screen(
    rnai_screen = TRUE,
    control_id = ids$control_id,
    mutant_id = ids$mutant_id,
    core_num = core_num,
    output_dir = output_dir,
    filename = file.path(
      "intermediate_files",
      paste0(context_label, "_GI")
    ),
    data_dir = gretta_data_dir,
    test = FALSE
  )

  perms <- GRETTA::GI_screen_perms(
    rnai_screen = TRUE,
    control_id = ids$control_id,
    mutant_id = ids$mutant_id,
    n_perm = n_perm,
    core_num = core_num,
    output_dir = output_dir,
    filename = file.path(
      "intermediate_files",
      paste0(context_label, "_GI_perms")
    ),
    data_dir = gretta_data_dir
  )

  screen_results_permed <- GRETTA::Append_perm_pval(
    screen_results,
    perms
  )

  write_csv(
    screen_results_permed,
    file.path(
      intermediate_dir,
      paste0(context_label, "_GI_perms_annotated.csv")
    )
  )

  screen_results_annotated <- annotate_rnai_results(
    screen_results_permed
  )

  write_csv(screen_results_annotated, final_file)

  if (make_plots) {

    genes_to_label <- screen_results_annotated %>%
      filter(GI_tier %in% c("Tier_1", "Tier_2")) %>%
      pull(GeneNames) %>%
      unique()

    screen_plot <- if (length(genes_to_label) == 0) {
      GRETTA::plot_screen(
        result_df = screen_results_annotated,
        label_genes = FALSE
      )
    } else {
      GRETTA::plot_screen(
        result_df = screen_results_annotated,
        label_genes = TRUE,
        gene_list = genes_to_label
      )
    }

    ggsave(
      filename = file.path(
        plots_dir,
        paste0(context_label, "_GI.pdf")
      ),
      plot = screen_plot,
      width = 8,
      height = 6,
      units = "in"
    )
  }
}

# ------------------------------------------------------------------------------
# Collect Tier 1/2 results
# ------------------------------------------------------------------------------

tier123_results <- pmap_dfr(
  screenable_contexts,
  function(
      GeneName,
      mut_group,
      disease,
      MS_status,
      n_control,
      n_homdel,
      n_thet_del,
      n_mutant,
      is_screenable) {

    context_label <- paste(
      GeneName,
      mut_group,
      safe_name(disease),
      MS_status,
      sep = "_"
    )

    result_file <- file.path(
      results_dir,
      paste0(
        context_label,
        "_GI_perms_annotated_prioritised.csv"
      )
    )

    if (!file.exists(result_file)) {
      return(tibble())
    }

    read_csv(result_file, show_col_types = FALSE) %>%
      filter(GI_tier %in% c("Tier_1", "Tier_2", "Tier_3")) %>%
      mutate(
        Query_gene = GeneName,
        Query_gene_group = mut_group,
        Query_disease_context = disease,
        MS_status = MS_status,
        Total_mutant_line_N = n_mutant,
        Total_control_line_N = n_control,
        Available_HomDel_line_N = n_homdel,
        Available_T_HetDel_line_N = n_thet_del
      )
  }
)

write_csv(
  tier123_results,
  file.path(
    output_dir,
    "RNAi_POG_BLOF_screen_results_Tier123.csv"
  )
)

message("RNAi screening workflow complete.")
